Update Checking-Tests.yml

diff --git a/.github/workflows/Checking-Tests.yml b/.github/workflows/Checking-Tests.yml
--- a/.github/workflows/Checking-Tests.yml
+++ b/.github/workflows/Checking-Tests.yml
@@ -19,10 +19,11 @@ jobs:
         with:
           dotnet-version: '8.0'
 
-      - name: Run Tests and Generate xUnit Results
+      - name: Run Tests
+        id: run-tests
         run: |
           mkdir -p test_results
-          dotnet test KraftKollen/KraftKollen.Tests/KraftKollen.Tests.csproj --logger "xunit;LogFileName=test_results/results.xml" > test_results/test_log.txt 2>&1
+          dotnet test KraftKollen/KraftKollen.Tests/KraftKollen.Tests.csproj --logger "xunit;LogFileName=test_results/results.xml" > test_results/test_log.txt 2>&1 || echo "Tests failed"
         continue-on-error: true
 
       - name: Upload Test Results
@@ -31,6 +32,6 @@ jobs:
           name: test-results
           path: test_results
 
-      - name: Check Test Status
-        if: failure()
+      - name: Fail Workflow on Test Failures
+        if: ${{ steps.run-tests.outcome == 'failure' }}
         run: exit 1
