Update PrTestFailureprV2.yml

diff --git a/.github/workflows/PrTestFailureprV2.yml b/.github/workflows/PrTestFailureprV2.yml
--- a/.github/workflows/PrTestFailureprV2.yml
+++ b/.github/workflows/PrTestFailureprV2.yml
@@ -9,23 +9,23 @@ on:
 jobs:
   test-and-report:
     runs-on: ubuntu-latest
-    
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup .NET 
+      - name: Setup .NET
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: '8.0'
 
       - name: Run Tests and Generate xUnit Results
+        id: run-tests
         run: |
           mkdir -p test_results
           # Kör tester och skapa logg
-          dotnet test KraftKollen/KraftKollen.Tests/KraftKollen.Tests.csproj --logger "xunit;LogFileName=test_results/results.xml" > test_results/test_log.txt 2>&1 || true
-          echo "Contents of test_results directory after running tests:"
-          ls -l test_results
+          dotnet test KraftKollen/KraftKollen.Tests/KraftKollen.Tests.csproj --logger "xunit;LogFileName=test_results/results.xml" > test_results/test_log.txt 2>&1
+        continue-on-error: true
 
       - name: Upload Test Results
         uses: actions/upload-artifact@v4
@@ -33,12 +33,18 @@ jobs:
           name: test-results
           path: test_results
 
+      - name: Set Test Status
+        if: failure()
+        run: |
+          echo "Test failures detected."
+          exit 1
+
   add-comment-to-pr:
     runs-on: ubuntu-latest
     needs: test-and-report
     permissions:
-      pull-requests: write  # Behörighet att skriva kommentarer till PR
-      contents: read        # Behörighet att läsa innehåll i repot
+      pull-requests: write
+      contents: read
 
     steps:
       - name: Download Artifact
@@ -86,7 +92,7 @@ jobs:
           echo "EOF" >> $GITHUB_ENV
 
       - name: Comment on Pull Request
-        uses: thollander/actions-comment-pull-request@v1
+        uses: thollander/actions-comment-pull-request@v3
         with:
           message: ${{ env.formatted_comment }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
